site_name: Defensoria SP
theme:
  palette:
    language: pt
    primary: red
    accent: green
  logo: assets/planejamento/logos/defensoria-logo.jpg
  favicon: images/favicon.jpg
  name: material
  features:
    - navigation.tabs
extra_css:
  - stylesheets/styles.css

dev_addr: "0.0.0.0:8000"
